In [1]:
import sys
import numpy as np
import math
from collections import deque 
from functools import reduce

# input = sys.stdin.readline


In [2]:
n = int(input())

 2


In [3]:
q = int(input())

 19


In [4]:
n_np = np.zeros([n, n])

In [5]:
for i in range(1, n+1):
    for j in range(1, n+1):
        n_np[i-1][j-1] = n * (i-1) + (j-1)

In [23]:
g_np = np.arange(n)
r_np = np.arange(n)
t = False

In [27]:
for _ in range(q):
    query = input()
    if query[0] == '3':
        t = not t
    else:
        qr = query.split()
        qa, qb = int(qr[1]), int(qr[2])
        if qr[0] == '1':
            if qa == qb:
                continue
            if not t:
                g_np[qa-1], g_np[qb-1] = g_np[qb-1], g_np[qa-1]
            else:
                r_np[qa-1], r_np[qb-1] = r_np[qb-1], r_np[qa-1]
        elif qr[0] == '2':
            if qa == qb:
                continue
            if not t:
                r_np[qa-1], r_np[qb-1] = r_np[qb-1], r_np[qa-1]
            else:
                g_np[qa-1], g_np[qb-1] = g_np[qb-1], g_np[qa-1]
        else:
            if not t:
                i_g = int(np.where(g_np == qa-1)[0])
                i_r = int(np.where(r_np == qb-1)[0])
#                 print(t)
#                 print(qa-1, i_g)
#                 print(qb-1, i_r)
                print(int(n_np[i_g][i_r]))
            else:
                i_g = int(np.where(g_np == qb-1)[0])
                i_r = int(np.where(r_np == qa-1)[0])
#                 print(t)
#                 print(qb-1, i_g)
#                 print(qa-1, i_r)
                print(int(n_np[i_g][i_r]))
                

 4 1 1


True
0 0
0 0
0


 4 1 2


True
1 1
0 0
2


 4 2 1


True
0 0
1 1
1


 4 2 2


True
1 1
1 1
3


 q


IndexError: list index out of range

In [ ]:
n_np.shape

In [ ]:
g_np[0], g_np[1] = g_np[1], g_np[0]

In [ ]:
g_np

In [ ]:
query

In [ ]:
(int, query.split())

In [ ]:
n_np[qa-1][qb-1]

In [ ]:
n_np[qb-1][qa-1]

In [ ]:
type(np.where(g_np == 0))

In [ ]:
int(np.where(g_np == 0)[0])

In [12]:
g_np, r_np, n_np

(array([0, 1]),
 array([0, 1]),
 array([[0., 1.],
        [2., 3.]]))

In [17]:
t

False