In [1]:
# chapter 4

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(3,)

In [7]:
a.dtype

dtype('int32')

In [8]:
a[0]

1

In [9]:
a[1]

2

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [13]:
b.dtype

dtype('int32')

In [14]:
b[0]

array([1, 2, 3])

In [16]:
b[1]

array([4, 5, 6])

In [17]:
b[0][0]

1

In [19]:
b[0, 0]

1

In [20]:
b[1, 2]

6

In [21]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [22]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
c.shape

(3, 4)

In [24]:
c[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
c[2:]

array([[ 9, 10, 11, 12]])

In [26]:
c[:2, 1]

array([2, 6])

In [27]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.full((3, 5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [30]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
# chapter 5

In [32]:
import numpy as np

In [33]:
a = np.array([[1, 2 ,3], [4, 5, 6]])

In [34]:
b = np.array([[1, 2 ,3], [4, 5, 6]])

In [35]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a + b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [37]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [39]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [40]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [41]:
a < 2

array([[ True, False, False],
       [False, False, False]])

In [42]:
array = np.array([1, 2, 3])

In [43]:
array

array([1, 2, 3])

In [46]:
list = [1, 2, 3]

In [47]:
list

[1, 2, 3]

In [48]:
list + [4]

[1, 2, 3, 4]

In [49]:
array + [4]

array([5, 6, 7])

In [50]:
array

array([1, 2, 3])

In [51]:
list

[1, 2, 3]

In [52]:
list2 = []

In [53]:
for e in list:
    list2.append(e + 4)

In [54]:
list2

[5, 6, 7]

In [55]:
list * 2

[1, 2, 3, 1, 2, 3]

In [56]:
array * 2

array([2, 4, 6])

In [57]:
list2 = []

In [58]:
for e in list:
    list2.append(e*2)

In [60]:
list2

[2, 4, 6]

In [62]:
list3 = [i * 2 for i in list]

In [63]:
list3

[2, 4, 6]

In [64]:
# chapter 6

In [65]:
import numpy as np

In [66]:
a = np.array([[1, 2], [3, 4]])

In [67]:
a

array([[1, 2],
       [3, 4]])

In [72]:
b = np.array([[6, 7], [8, 9]])

In [73]:
b

array([[6, 7],
       [8, 9]])

In [74]:
a * b

array([[ 6, 14],
       [24, 36]])

In [75]:
np.dot(a, b)

array([[22, 25],
       [50, 57]])

In [76]:
np.dot(b, a)

array([[27, 40],
       [35, 52]])

In [77]:
a.dot(b)

array([[22, 25],
       [50, 57]])

In [78]:
b.dot(a)

array([[27, 40],
       [35, 52]])

In [79]:
c = [[1, 2], [3, 4]]

In [80]:
type(c)

list

In [81]:
c = np.array(c)

In [82]:
type(c)

numpy.ndarray

In [83]:
d = [[1, 2, 3, 4, 5], [2, 3]]

In [85]:
d = np.array(d)

In [86]:
d

array([list([1, 2, 3, 4, 5]), list([2, 3])], dtype=object)

In [87]:
type(d)

numpy.ndarray

In [89]:
c = c.tolist()

In [90]:
c

[[1, 2], [3, 4]]

In [91]:
# chapter 7

In [92]:
import numpy as np

In [94]:
# 一様分布
np.random.rand(10)

array([0.69475961, 0.21250381, 0.82889522, 0.23567257, 0.57180284,
       0.3967933 , 0.08340718, 0.48796427, 0.26868272, 0.63044927])

In [95]:
np.random.rand(10, 10)

array([[0.06016937, 0.54070729, 0.16227546, 0.20773961, 0.72584692,
        0.18754734, 0.03662516, 0.03388228, 0.84468117, 0.27167179],
       [0.40093232, 0.76933461, 0.75515898, 0.58327735, 0.17877307,
        0.87321009, 0.07506717, 0.84415821, 0.73543689, 0.38013049],
       [0.64576673, 0.89265902, 0.18430512, 0.26372933, 0.04989274,
        0.14904234, 0.9011857 , 0.42007746, 0.28495056, 0.24395227],
       [0.34121816, 0.80723196, 0.60321617, 0.91687998, 0.75281587,
        0.30692665, 0.83566736, 0.45546712, 0.55948447, 0.86121877],
       [0.53153041, 0.32495454, 0.10664953, 0.90516288, 0.97933585,
        0.65804383, 0.70622842, 0.5410275 , 0.20342076, 0.5168377 ],
       [0.54939019, 0.42855147, 0.71118509, 0.84453974, 0.48110366,
        0.27122892, 0.28230932, 0.42368906, 0.50380447, 0.641693  ],
       [0.0446018 , 0.66609349, 0.26574942, 0.37624638, 0.29153693,
        0.77087558, 0.71805907, 0.37408467, 0.02059278, 0.75652024],
       [0.04924588, 0.33680779, 0.5719613

In [96]:
a = np.random.rand(10, 10)

In [97]:
a.shape

(10, 10)

In [98]:
# 正規分布
np.random.randn(1)

array([0.69452506])

In [99]:
rand5000 = np.random.randn(5000, 5000)

In [100]:
rand5000.shape

(5000, 5000)

In [101]:
rand5000.mean()

0.00031042789117025294

In [102]:
rand5000_2 = np.random.randn(5000, 5000)

In [103]:
rand5000_2.shape

(5000, 5000)

In [104]:
rand5000_2.mean()

-3.512307496671161e-06

In [105]:
rand5000_2.std()

0.9999204101976528

In [106]:
rand5000.std()

0.9998896272901838

In [108]:
# 整数の乱数 1つ手前まで
np.random.randint(100)

38

In [109]:
np.random.randint(1, 30, 30)

array([ 4,  7, 21, 25, 20, 16, 13,  9, 11,  6,  9, 26,  4, 29,  8,  9, 15,
        3, 25, 27,  3, 20, 25, 28, 27,  8, 27, 17,  9,  2])

In [110]:
randint30 = np.random.randint(1, 30, (30, 30))

In [111]:
randint30

array([[14, 20,  2, 13, 26, 17, 18, 24,  2, 14,  6, 14, 21, 11, 11, 29,
        11, 16,  4, 12, 12,  4, 20,  7, 29,  7, 28, 13, 21,  5],
       [ 6, 20, 13, 17, 25,  4, 18, 21,  6,  8, 25, 18,  9,  9,  7, 18,
        11,  5, 28,  4, 13,  7, 26, 23,  8,  8,  6, 20, 19,  4],
       [ 3,  3,  5, 18, 27, 29,  1,  3, 20,  6,  9,  1,  8, 10, 23, 18,
        13, 25, 17, 27, 10,  2,  1,  9, 10, 15, 12, 22,  1, 20],
       [17, 14, 29,  8, 14,  7, 15, 20, 26, 27, 19, 24, 27, 29, 20, 28,
         3, 21,  3, 11, 25, 18, 27, 17, 16, 10,  1, 14, 27, 20],
       [25, 29, 28,  6, 16,  1, 27, 25,  9,  3,  4, 18,  1, 21, 28,  3,
        19, 10, 27, 15,  6, 22, 20, 18, 12, 10,  3,  8,  3, 20],
       [21, 27, 26,  7,  5, 20, 28, 23, 13, 27, 28, 23, 29, 15,  3, 14,
        24, 21, 25, 24, 22, 19, 15, 17,  1,  8, 21, 22, 14, 19],
       [28,  3,  9, 26, 20, 28,  4, 16, 13, 23,  6, 28, 25,  6, 16, 21,
        28,  5, 26, 26, 27, 22, 26, 17,  4, 22,  2,  9, 20,  7],
       [ 6, 23, 17, 26, 28, 21, 26, 24,  

In [112]:
randint30.shape

(30, 30)

In [113]:
# 乱数発生の初期化　最初の乱数を指定する
np.random.seed(100)

In [114]:
np.random.randn()

-1.7497654730546974

In [115]:
np.random.randn()

0.34268040332750216

In [116]:
np.random.randn()

1.153035802563644

In [118]:
np.random.seed(100)
np.random.randn()

-1.7497654730546974

In [119]:
# chapter 8

In [120]:
import numpy as np

In [121]:
# 逆行列の生成
a = np.array([[2, 5], [1, 3]])

In [122]:
a

array([[2, 5],
       [1, 3]])

In [123]:
b = np.linalg.inv(a)

In [124]:
b

array([[ 3., -5.],
       [-1.,  2.]])

In [125]:
a.dot(b)

array([[1., 0.],
       [0., 1.]])

In [126]:
b.dot(a)

array([[1., 0.],
       [0., 1.]])

In [127]:
# 転置行列
c = np.array([[3, 1], [2, 6], [4, 5]])

In [128]:
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [129]:
c.T

array([[3, 2, 4],
       [1, 6, 5]])

In [130]:
a

array([[2, 5],
       [1, 3]])

In [131]:
a.T

array([[2, 1],
       [5, 3]])

In [132]:
# 対角成分の取得
d = np.eye(3)

In [133]:
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.diag(d)

array([1., 1., 1.])

In [135]:
# ベクトルの内積と外積
a = np.array([1, 2, 3, 4])

In [136]:
a

array([1, 2, 3, 4])

In [144]:
b = np.array([5, 6, 7, 8])

In [145]:
b

array([5, 6, 7, 8])

In [146]:
np.inner(a, b)

70

In [140]:
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [147]:
c = np.array([5, 6, 7, 8, 9])

In [148]:
np.outer(a, c)

array([[ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

In [149]:
# chapter 9

In [150]:
import numpy as np

In [151]:
# sin, cos, tan にはラジアンで渡す
np.tan(45)

1.6197751905438615

In [152]:
# 度数からラジアンに変換
rd = np.radians(45)

In [153]:
rd

0.7853981633974483

In [154]:
np.tan(rd)

0.9999999999999999

In [155]:
rd = np.radians(90)

In [156]:
rd

1.5707963267948966

In [157]:
np.sin(rd)

1.0

In [158]:
np.e

2.718281828459045

In [160]:
np.exp(2)

7.38905609893065

In [161]:
a = np.array([1, 2, 3, 4 ,5])

In [162]:
# ネイピア数の指数
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [170]:
# 自然対数
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [164]:
b = np.array([-5, -1, -1, 0, 10, 15, -1, -2])

In [165]:
# 正：1、０、負：-1
np.sign(b)

array([-1, -1, -1,  0,  1,  1, -1, -1])

In [166]:
c = np.random.randn(10)

In [167]:
c

array([ 0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,  0.51421884,
        0.22117967, -1.07004333, -0.18949583,  0.25500144, -0.45802699])

In [168]:
# 小数点を四捨五入
np.rint(c)

array([ 0.,  1., -0.,  1.,  1.,  0., -1., -0.,  0., -0.])

In [169]:
# 小数点と整数部を分ける
np.modf(c)

(array([ 0.3426804 ,  0.1530358 , -0.25243604,  0.98132079,  0.51421884,
         0.22117967, -0.07004333, -0.18949583,  0.25500144, -0.45802699]),
 array([ 0.,  1., -0.,  0.,  0.,  0., -1., -0.,  0., -0.]))

In [171]:
b = np.array([[2,7,10,2],[3,43,1,9]])
b[:,2]

array([10,  1])