In [1]:
import sys
import numpy as np
import math
import collections
import copy
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations
from bisect import bisect_right
from bisect import bisect_left


In [34]:
# 素数のリスト作成
def get_prime_list(number):
    is_prime = np.ones(number+1, dtype=bool)
    is_prime[:2] = False
    num_sqrt = np.sqrt(number)
    for i in range(2, int(num_sqrt)+1):
        if (is_prime[i]):
            is_prime[i*2::i] = False
    prime_list = np.arange(number+1)[is_prime]
    return prime_list

In [35]:
prime_list = get_prime_list(10000)

In [36]:
prime_list

array([   2,    3,    5, ..., 9949, 9967, 9973])

In [23]:
# 素数のリスト作成（boolで返却）
def get_prime_list(number):
    is_prime = np.ones(number+1, dtype=bool)
    is_prime[:2] = False
    num_sqrt = np.sqrt(number)
    for i in range(2, int(num_sqrt)+1):
        if (is_prime[i]):
            is_prime[i*2::i] = False
    return is_prime

In [24]:
prime_list = get_prime_list(100)

In [26]:
prime_list, prime_list.shape

(array([False, False,  True,  True, False,  True, False,  True, False,
        False, False,  True, False,  True, False, False, False,  True,
        False,  True, False, False, False,  True, False, False, False,
        False, False,  True, False,  True, False, False, False, False,
        False,  True, False, False, False,  True, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False,  True, False,  True, False,
        False, False, False, False,  True, False, False, False,  True,
        False,  True, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False,
        False, False]),
 (101,))

In [27]:
num_np = np.array(np.arange(101))

In [28]:
num_np[:][prime_list]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [31]:
[x for x in range(101)][prime_list == True]

TypeError: only integer scalar arrays can be converted to a scalar index

In [37]:
# 約数のリスト作成
def get_divisor_list(number):
    number_sqrt = int(np.sqrt(number)) + 1
    divisors = []
    for i in range(1, int(number_sqrt)):
        if number % i == 0:
            # 割り切れたので約数
            divisors.append(i)
            divisors.append(number // i)
    return divisors


In [43]:
divisor_list1 = get_divisor_list(64)

In [44]:
divisor_list1

[1, 64, 2, 32, 4, 16, 8, 8]

In [40]:
# 約数のリスト作成
def get_divisor_list_without_sqrt(number):
    number_sqrt = int(np.sqrt(number)) + 1
    divisors = []
    for i in range(1, int(number_sqrt)):
        if number % i == 0:
            # 割り切れたので約数
            divisors.append(i)
            if i ** 2 != number:
                divisors.append(number // i)
    return divisors


In [46]:
divisor_list2 = get_divisor_list_without_sqrt(64)

In [47]:
divisor_list2

[1, 64, 2, 32, 4, 16, 8]

In [1]:
# x の y 乗を d で割った余りを求める
def powmod(x, y, d):
    ret = 1
    for _ in range(1, y+1):
        ret = ret * x % d
    return ret

In [2]:
ans = powmod(10, 869121, 10**9+7) - powmod(9, 869121, 10**9+7) * 2 + powmod(8, 869121, 10**9+7)

In [3]:
ans % (10**9+7)

2511445

In [1]:
# ユークリッドの互除法で最大公約数を求める
def get_gcd(a, b):
    if b == 0:
        return a
    
    return get_gcd(b, a%b)


In [3]:
get_gcd(390, 273)

39

In [2]:
# 組合せの数を算出
def combinations_count(n, r):
    return math.factorial(n) // (math.factorial(n-r) * math.factorial(r))

In [4]:
combinations_count(4, 2)

6