In [ ]:
# 累積和

In [1]:
import sys
import numpy as np
import math
import collections
import copy
import itertools
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations

# input = sys.stdin.readline

In [2]:
A = [1,6,3,8,4,2,9,5,7]

In [3]:
B = np.zeros(len(A))

In [4]:
B[0] = A[0]

In [5]:
for i in range(1, len(A)):
    B[i] = A[i]+B[i-1]

In [6]:
B

array([ 1.,  7., 10., 18., 22., 24., 33., 38., 45.])

In [7]:
D = B[3:] - B[:-3]

In [8]:
D, int(max(D))

(array([17., 15., 14., 15., 16., 21.]), 21)

In [9]:
B[3:], B[:-3]

(array([18., 22., 24., 33., 38., 45.]), array([ 1.,  7., 10., 18., 22., 24.]))

In [27]:
C = []

In [28]:
C.append(A[0])

In [29]:
for i in range(1, len(A)):
    C.append(A[i]+C[i-1])

In [48]:
ans = C[2]
for i in range(3, len(C)):
    ans = max(ans, C[i]-C[i-3])

In [49]:
ans

21

In [47]:
len(C),C

(9, [1, 7, 10, 18, 22, 24, 33, 38, 45])

In [6]:
# numpy cumsum

In [7]:
D = np.cumsum(A)

In [8]:
D

array([ 1,  7, 10, 18, 22, 24, 33, 38, 45], dtype=int32)

In [9]:
# itertools accumulate

In [13]:
E = list(itertools.accumulate(A))

In [14]:
E

[1, 7, 10, 18, 22, 24, 33, 38, 45]

In [15]:
F = np.diff(D)

In [16]:
F

array([6, 3, 8, 4, 2, 9, 5, 7], dtype=int32)

In [31]:
F2 = np.insert(F, 0, D[0])

In [32]:
F2

array([1, 6, 3, 8, 4, 2, 9, 5, 7], dtype=int32)

In [2]:
# 二次元

In [3]:
H, W = map(int, input().split())

 4 5


In [6]:
An = [list(map(int, input().split())) for _ in range(H)]

 1 8 7 3 2
 9 1 3 4 6
 3 5 8 1 4
 2 7 3 2 5


In [8]:
len(An)

4

In [70]:
An_np = np.array(An)

In [9]:
Q = int(input())

 3


In [22]:
Qn = [list(map(int, input().split())) for _ in range(Q)]

 1 3 2 5
 0 2 1 3
 0 4 0 5


In [29]:
Cm = np.zeros([H+1, W+1])

In [30]:
for i in range(H):
    for j in range(W):
#         print(i, j)
        Cm[i+1][j+1] = Cm[i+1][j] + Cm[i][j+1] - Cm[i][j] + An[i][j]

In [31]:
Cm[0]

array([0., 0., 0., 0., 0., 0.])

In [32]:
Cm[1]

array([ 0.,  1.,  9., 16., 19., 21.])

In [33]:
Cm[2]

array([ 0., 10., 19., 29., 36., 44.])

In [34]:
Cm[3]

array([ 0., 13., 27., 45., 53., 65.])

In [35]:
Cm[4]

array([ 0., 15., 36., 57., 67., 84.])

In [79]:
for Q in Qn:
    x1, x2, y1, y2 = Q
    print(Cm[x2][y2] , Cm[x2][y1] , Cm[x1][y2] , Cm[x1][y1])
    print(Cm[x2][y2] - Cm[x2][y1] - Cm[x1][y2] + Cm[x1][y1])

65.0 27.0 21.0 9.0
26.0
29.0 10.0 0.0 0.0
19.0
84.0 0.0 0.0 0.0
84.0


In [76]:
np.sum(An_np[:3, 1:])

52

In [75]:
An_np[:3, 2:]

array([[7, 3, 2],
       [3, 4, 6],
       [8, 1, 4]])

In [78]:
65-44-53+36

4

In [90]:
Cm_0 = np.cumsum(An_np, axis=0)

In [91]:
Cm_1 = np.cumsum(An_np, axis=1)

In [92]:
Cm_2 = Cm_0 + Cm_1

In [ ]:
Cm_2 = Cm_2 - Cm

In [6]:
A1 = [x for x in range(1, 10)]

In [7]:
B1 = [0 for _ in range(10)]

In [8]:
for i in range(10-1):
    B1[i+1] = B1[i] + A1[i]

In [14]:
B1[7-1]-B1[3-1]

18

In [11]:
B1[1]-B1[0]

1