In [1]:
def word_search(doc_list, keyword):
    for i, doc in enumerate(doc_list):
        doc = doc.upper().replace('.', ' ')
        keyword = keyword.upper() + " "
        if doc.startswith(keyword) or (" " + keyword) in doc:
            print('[{}]'.format(i))

In [2]:
doc_list = ["The Learn Python Challenge Casino.", "They bought a car", "Casinoville"]
word_search(doc_list, 'casino')

[0]


In [6]:
import numpy as np

In [2]:
np.e

2.718281828459045

In [4]:
np.e ** (-500/1000)

0.6065306597126334

In [5]:
1-(np.power(np.e, -1/2))

0.3934693402873666

In [6]:
1-np.e ** (-500/1000)

0.3934693402873666

In [7]:
np.e**(-3)

0.04978706836786395

In [8]:
np.e**(-3) * 3**2 / 2 * 1

0.22404180765538778

In [4]:
import math

In [7]:
np.e**(-3) * 3**2 / math.factorial(2)

0.22404180765538778

In [8]:
# 階乗
math.factorial(6)

720

In [53]:
s = ["2",
    "100 5 700",
    "50 2 300",
    "order 13 100 4",
    "order 12 100 2",
    "order 11 100 1"]


In [54]:
m = int(s.pop(0))

In [55]:
# menu = []
# for _ in range(m):
#     l = s.pop(0).split()[1:]
#     menu.append(s.pop(0))

In [56]:
menu = [list(map(int, s.pop(0).split())) for _ in range(m)]

In [57]:
order = []

In [58]:
for item in s:
    order.append([list(map(int, item.split()[1:]))])

In [59]:
order_n = np.array(order).reshape(-1, 3)

In [60]:
for i in range(order_n.shape[0]):
    for j in range(len(menu)):
        if (order_n[i][1] == menu[j][0]):
            if order_n[i][2] > menu[j][1]:
                print("sold out {0}".format(order_n[i][0]))
            else:
                for _ in range(order_n[i][2]):
                    print("received order {0} {1}".format(order_n[i][0], order_n[i][1]))
                menu[j][1] -= order_n[i][2]

received order 13 100
received order 13 100
received order 13 100
received order 13 100
sold out 12
received order 11 100


In [42]:
order_n.shape

(3, 3)

In [14]:
s[0]

'2'

In [12]:
import numpy as np
from collections import deque 

In [76]:
lines = ["7 3",
      "1",
      "2",
      "3"]


In [77]:
n, q = map(int, lines.pop(0).split())

In [78]:
idx = np.arange(n)

In [79]:
d_card = deque([i for i in range(1, n+1)])

In [80]:
for i in range(1, n):
    card = d_card.popleft()
    c_idx = idx[card-1]
    d_card.insert(i, card)
    print(idx)
    idx[i >= idx] -= 1 
    print(idx)
    idx[card-1] = i
    print(idx)
    print(idx)
    print(d_card)

[0 1 2 3 4 5 6]
[-1  0  2  3  4  5  6]
[1 0 2 3 4 5 6]
[1 0 2 3 4 5 6]
deque([2, 1, 3, 4, 5, 6, 7])
[1 0 2 3 4 5 6]
[ 0 -1  1  3  4  5  6]
[0 2 1 3 4 5 6]
[0 2 1 3 4 5 6]
deque([1, 3, 2, 4, 5, 6, 7])
[0 2 1 3 4 5 6]
[-1  1  0  2  4  5  6]
[3 1 0 2 4 5 6]
[3 1 0 2 4 5 6]
deque([3, 2, 4, 1, 5, 6, 7])
[3 1 0 2 4 5 6]
[ 2  0 -1  1  3  5  6]
[2 0 4 1 3 5 6]
[2 0 4 1 3 5 6]
deque([2, 4, 1, 5, 3, 6, 7])
[2 0 4 1 3 5 6]
[ 1 -1  3  0  2  4  6]
[1 5 3 0 2 4 6]
[1 5 3 0 2 4 6]
deque([4, 1, 5, 3, 6, 2, 7])
[1 5 3 0 2 4 6]
[ 0  4  2 -1  1  3  5]
[0 4 2 6 1 3 5]
[0 4 2 6 1 3 5]
deque([1, 5, 3, 6, 2, 7, 4])


In [81]:
for num in lines:
    nu = int(num)
    print(idx[nu-1]+1)

1
5
3


In [4]:
lines[0]

'4 4'

In [46]:
idx

array([ 3,  1, -1,  0])