In [6]:
import sys
import numpy as np
import math
import collections
import copy
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations

# input = sys.stdin.readline

In [1]:
N = int(input())

 3


In [2]:
Dn = [list(map(int, input().split())) for _ in range(N)]

 3 2 1
 2 2 1
 1 1 1


In [3]:
Q = int(input())

 3


In [4]:
Pn = [int(input()) for _ in range(Q)]

 1 
 4
 9


In [7]:
Cm_np = np.zeros([N+1, N+1])

In [8]:
for i in range(N):
    for j in range(N):
        Cm_np[i+1, j+1] = Cm_np[i, j+1] + Cm_np[i+1, j] - Cm_np[i, j] + Dn[i][j]

In [20]:
dp = [0 for _ in range(N*N+1)]
for x1 in range(N+1):
    for x2 in range(x1+1, N+1):
        for y1 in range(N+1):
            for y2 in range(y1+1, N+1):
                tt = (x2-x1) * (y2-y1)
                cnt = Cm_np[x2, y2] - Cm_np[x1, y2] - Cm_np[x2, y1] + Cm_np[x1, y1]
#                 print(x1, x2, y1, y2)
#                 print(Cm_np[x2, y2], Cm_np[x1, y2], Cm_np[x2, y1], Cm_np[x1, y1])
#                 print(dp[tt], cnt)
#                 if tt == 2:
#                     print(i, ic, j, jc, tt, cnt)
#                     print(Cm_np[i+(ic-1), j+(jc-1)], Cm_np[i-1, j], Cm_np[i, j-1], Cm_np[i-1, j-1])
                dp[tt] = max(dp[tt], cnt)

In [21]:
for p in Pn:
    print(int(max(dp[:p+1])))

3
9
14


In [42]:
dp[1],dp[4],dp[9]

(3.0, 9.0, 14.0)

In [12]:
Cm_np[0]

array([0., 0., 0., 0.])

In [13]:
Cm_np[1]

array([0., 3., 5., 6.])

In [14]:
Cm_np[2]

array([ 0.,  5.,  9., 11.])

In [15]:
Cm_np[3]

array([ 0.,  6., 11., 14.])

In [16]:
50**4

6250000

In [12]:
Cm_np[:, :]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  3.,  5.,  6.],
       [ 0.,  5.,  9., 11.],
       [ 0.,  6., 11., 14.]])

In [14]:
Cm_np[:, 0], Cm_np[:, 1], Cm_np[:, 2], Cm_np[:, 3]

(array([0., 0., 0., 0.]),
 array([0., 3., 5., 6.]),
 array([ 0.,  5.,  9., 11.]),
 array([ 0.,  6., 11., 14.]))

In [22]:
np.log10(200000)

5.301029995663981

In [25]:
200000*np.log2(200000)

3521928.0948873623