In [ ]:
# WA

In [1]:
import sys
import numpy as np
import math
import collections
import copy
import decimal
import itertools
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations
from functools import lru_cache

In [111]:
N = int(input())

 7


In [112]:
An = list(map(int, input().split()))

 1 1 1 1 2 3 4


In [113]:
d = np.arange(1, N+1)
di = np.abs(d - An)
f = math.floor(di.mean())
c = math.ceil(di.mean())
dif = np.abs(di - f)
dic = np.abs(di - c)
dim = np.abs(di - np.median(di))
dimp = np.abs(di - np.median(di)+1)
dimm = np.abs(di - np.median(di)-1)


In [114]:
ans = min(dif.sum(), dic.sum(), dim.sum(), dimp.sum(), dimm.sum())

In [115]:
print(ans)

6


In [105]:
10**9 

1000000000

In [54]:
np.arange(1, N+1)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
d

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
type(d)

numpy.ndarray

In [57]:
di, type(di)

(array([0, 1, 2, 3, 3, 3, 3]), numpy.ndarray)

In [58]:
di.mean()

2.142857142857143

In [59]:
di.sum()

15

In [62]:
abs(di.sum()-math.floor(di.mean())*N), abs(di.sum()-math.ceil(di.mean())*N)

(1, 6)

In [90]:
np.median(di)

3.0