In [3]:
import sys
import numpy as np
import math
import collections
import copy
import decimal
import itertools
import re
import bisect
import scipy
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations
from functools import lru_cache
from scipy.special import comb
from numba import njit
from bisect import bisect_right
from bisect import bisect_left

In [1]:
N = int(input())

 4


In [4]:
XY0 = np.array(list(map(int, input().split())))

 1 1


In [5]:
XYn = np.array(list(map(int, input().split())))

 2 2


In [6]:
n_Center = (XY0 + XYn) / 2
n_0 = XY0 - n_Center
Dir = math.atan2(n_0[1], n_0[0])
Dir2 = Dir + math.radians(360 / N)
mat = np.array((math.cos(Dir2), -math.sin(Dir2), math.sin(Dir2), math.cos(Dir2))).reshape(2, 2)
XY1 = np.dot(mat, n_0) + n_Center

In [7]:
n_0 = XY0 - n_Center

In [10]:
n_Center, n_0, Dir, Dir2, math.degrees(Dir), math.degrees(Dir2)

(array([1.5, 1.5]),
 array([-0.5, -0.5]),
 -2.356194490192345,
 -0.7853981633974483,
 -135.0,
 -45.0)

In [12]:
mat, XY1

(array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]),
 array([0.79289322, 1.5       ]))

In [13]:
1J

1j