In [2]:
import numpy as np
a = np.array([[2, 4], [0, 4], [7, 9], [3, 7]])
b = np.array([[9, 2], [4, 1], [1, 7], [0, 2]])

In [2]:
a + b

array([[11,  6],
       [ 4,  5],
       [ 8, 16],
       [ 3,  9]])

In [3]:
c = np.array([[1, 3, 7], [2, 9, 0]])
c + b

ValueError: operands could not be broadcast together with shapes (2,3) (4,2) 

In [4]:
6 * c

array([[ 6, 18, 42],
       [12, 54,  0]])

In [5]:
d = np.array([[6, 3], [0, 1]])
d / 3

array([[2.        , 1.        ],
       [0.        , 0.33333333]])

In [6]:
(5 * e) - f + (g / 6)

NameError: name 'e' is not defined

In [7]:
a = np.array([[2, 5], [1, 9], [0, 3]])
b = np.array([[2], [3]])

np.dot(a, b)

array([[19],
       [29],
       [ 9]])

In [8]:
c = np.array([[1, 4], [2, 0], [8, 1], [3, 5]])
d = np.array([[1], [3]])

np.dot(c, d)

array([[13],
       [ 2],
       [11],
       [18]])

In [10]:
e = np.array([[1, 180], [1, 176], [1, 156], [1, 160], [1, 173]])
f = np.array([[15], [0.32]])

np.dot(e, f)

array([[72.6 ],
       [71.32],
       [64.92],
       [66.2 ],
       [70.36]])

In [11]:
a = np.array([[1,3],[6,1],[2,0]])
b = np.array([[0,2],[11,7]])

np.dot(a, b)

array([[33, 23],
       [11, 19],
       [ 0,  4]])

In [12]:
c = np.array([[2,1,0],[9,6,2]])
d = np.array([[8,0,2],[1,3,1],[7,4,0]])

np.dot(c, d)

array([[17,  3,  5],
       [92, 26, 24]])

In [13]:
e = np.array([[1,180],[1,176],[1,156],[1,160]])
d = np.array([[15,8,-7],[0.32,0.43,0.62]])

np.dot(e, d)

array([[ 72.6 ,  85.4 , 104.6 ],
       [ 71.32,  83.68, 102.12],
       [ 64.92,  75.08,  89.72],
       [ 66.2 ,  76.8 ,  92.2 ]])

In [3]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [4]:
np.dot(b, a)

array([[23, 34],
       [31, 46]])

In [5]:
3 * 4 == 4 * 3

True

In [6]:
c = np.array([[2,1],[4,3]])
a.dot(b).dot(c)

array([[126,  85],
       [286, 193]])

In [8]:
e = np.dot(a, b)
e

array([[19, 22],
       [43, 50]])

In [9]:
d = np.dot(b, c)
d

array([[34, 23],
       [46, 31]])

In [10]:
e.dot(c)

array([[126,  85],
       [286, 193]])

In [11]:
a.dot(d)

array([[126,  85],
       [286, 193]])

In [12]:
eye = np.eye(2)
eye

array([[1., 0.],
       [0., 1.]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
np.dot(a, eye)

array([[1., 2.],
       [3., 4.]])

In [15]:
np.dot(eye, a)

array([[1., 2.],
       [3., 4.]])

In [16]:
a

array([[1, 2],
       [3, 4]])

In [17]:
# chapter 8

In [18]:
import numpy as np
a = np.array([[2,5],[1,3]])
b = np.array([[3,-5],[-1,2]])

np.dot(a, b)

array([[1, 0],
       [0, 1]])

In [19]:
np.dot(b, a)

array([[1, 0],
       [0, 1]])

In [22]:
# 逆行列を求める
np.linalg.inv(a)

array([[ 3., -5.],
       [-1.,  2.]])

In [23]:
c = np.array([[3,1],[2,6],[4,5]])
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [25]:
# 転置
c.T

array([[3, 2, 4],
       [1, 6, 5]])