In [ ]:
# TLE

In [52]:
import sys
import numpy as np
import math

from collections import deque 
from functools import reduce
from functools import lru_cache

# input = sys.stdin.readline

In [85]:
n = int(input())

 200


In [97]:
n_np = np.zeros([n**3, 3])

In [98]:
idx = 0
for i in range(1, n+1):
    for j in range(1, n+1):
        for k in range(1, n+1):
            n_np[idx] = [i, j, k] 
#             n_np[idx][0] = i
#             n_np[idx][1] = j
#             n_np[idx][2] = k
            idx += 1
n_np = n_np.astype('int16')           

In [87]:
numbers = []
for i in range(1, n+1):
    for j in range(1, n+1):
        for k in range(1, n+1):
            numbers.append([i, j, k])
n_np = np.array(numbers)

In [93]:
gcd_np1 = np.gcd(n_np[:, 0], n_np[:, 1])
gcd_np2 = np.gcd(gcd_np1, n_np[:, 2])

print(int(gcd_np2.sum()))

10813692


In [36]:
n_np[:, 0], n_np[:, 1], n_np[:, 2]

(array([1., 1., 1., 1., 2., 2., 2., 2.]),
 array([1., 1., 2., 2., 1., 1., 2., 2.]),
 array([1., 2., 1., 2., 1., 2., 1., 2.]))

In [42]:
n_np[0], n_np[0].shape

(array([1., 1., 1.]), (3,))

In [67]:
n_np[:, 0].flatten().shape

(8,)

In [71]:
n_np.dtype

dtype('float64')