In [24]:
import collections

In [42]:
N = int(input())

 3


In [43]:
An = list(map(int, input().split()))

 1 2 2


In [44]:
Bn = list(map(int, input().split()))

 3 1 2


In [54]:
Cn = list(map(int, input().split()))

 2  3 1


In [55]:
An_c = collections.Counter(An)
Cn_c = collections.Counter(Cn)
ans = 0
for i, B in enumerate(Bn, 1):
    if B in An_c:
        ans += Cn_c[i] * An_c[B]


In [56]:
print(ans)

3


In [62]:
An_c, Cn_c

(Counter({1: 1, 2: 2}), Counter({2: 1, 3: 1, 1: 1}))

In [57]:
Cn.count(2)

1

In [58]:
import numpy as np

In [59]:
An_n = np.array(An) - 1
Bn_n = np.array(Bn) - 1
Cn_n = np.array(Cn) - 1
Dn = Bn_n[Cn_n]
cnt_A = np.bincount(An_n, minlength=N)
cnt_B = np.bincount(Dn, minlength=N)


In [60]:
An_n, Bn_n, Cn_n, Dn, cnt_A, cnt_B

(array([0, 1, 1]),
 array([2, 0, 1]),
 array([1, 2, 0]),
 array([0, 1, 2]),
 array([1, 2, 0], dtype=int64),
 array([1, 1, 1], dtype=int64))

In [61]:
sum(cnt_A * cnt_B)

3

In [ ]:
# TLE

In [25]:
An_c = collections.Counter(An)
Cn_c = collections.Counter(Cn)
ans = 0
for A, cnt in An_c.items():
    for i, B in enumerate(Bn):
        if A == B:
            ans += Cn_c[i+1] * cnt
