In [1]:
import sys
import numpy as np
import math
import collections
import copy
import decimal
import itertools
import re
import bisect
import scipy
import heapq
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations
from functools import lru_cache
from scipy.special import comb
from numba import njit
from bisect import bisect_right
from bisect import bisect_left

In [1]:
N = int(input())

 3


In [2]:
An = [list(map(int, input().split())) for _ in range(N)]

 0 1 1 
 1 0 0
 0 1 0


In [3]:
Bn = [list(map(int, input().split())) for _ in range(N)]

 1 1 0
 0 0 1
 1 1 1


In [22]:
def solve2(An_n):
    for i in range(N):
        for j in range(N):
            if An_n[i][j] == 0:
                continue
            if Bn_np[i][j] != 1:
                return False
    return True

In [24]:
def solve():
    if solve2(An_np):
        return True
    if solve2(An_n2):
        return True
    if solve2(An_n3):
        return True
    if solve2(An_n4):
        return True
    return False

In [25]:
import numpy as np
An_np = np.zeros([N, N])
Bn_np = np.zeros([N, N])
for i, (A, B) in enumerate(zip(An, Bn)):
    for j, (a, b) in enumerate(zip(A, B)):
        An_np[i][j] = a
        Bn_np[i][j] = b
An_n2 = np.rot90(An_np).copy()
An_n3 = np.rot90(An_np, 2).copy()
An_n4 = np.rot90(An_np, 3).copy()


In [26]:
print('Yes' if solve() else 'No')

Yes


In [ ]:
# 解説を読んで実装

In [10]:
import numpy as np
def solve():
    An_n = np.array(An)
    Bn_n = np.array(Bn)
    for _ in range(4):
        if np.min(Bn_n - An_n) >= 0:
            return True
        An_n = np.rot90(An_n)
    return False

In [21]:
print('Yes' if solve() else 'No')

Yes


In [22]:
import numpy as np
def solve():
    An_n = np.array(An)
    Bn_n = np.array(Bn)
    for _ in range(4):
        if np.all(Bn_n >= An_n):
            return True
        An_n = np.rot90(An_n)
    return False

In [23]:
print('Yes' if solve() else 'No')

Yes


In [16]:
def rotate(An_c):
    ret = deepcopy(An_c)
    for i in range(N):
        for j in range(N):
            ret[N-1-j][i] = An_c[i][j]
    return ret

In [17]:
def check(An_c):
    for i in range(N):
        for j in range(N):
            if An_c[i][j] == 0:
                continue
            if Bn[i][j] != 1:
                return False
    return True

In [18]:
from copy import deepcopy
def solve():
    An_c = deepcopy(An)
    for _ in range(4):
        if check(An_c):
            return True
        An_c = rotate(An_c)
    return False

In [19]:
print('Yes' if solve() else 'No')

Yes


In [ ]:
def solve(f1, f2):
    

In [6]:
for f1, f2 in ([True, True], [True, False], [False, True], [False, False]):
    print(f1, f2)

True True
True False
False True
False False


In [14]:
An_np, Bn_np, An_n2

(array([[0., 1., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[1., 1., 0.],
        [0., 0., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0.],
        [1., 0., 1.],
        [0., 1., 0.]]))

In [28]:
an = np.array(An)

In [29]:
an

array([[0, 1, 1],
       [1, 0, 0],
       [0, 1, 0]])