In [ ]:
# maspy さんのコードをパクり

In [1]:
import sys
import numpy as np
import math
import collections
import copy
import decimal
from collections import deque 
from functools import reduce
from itertools import product
from itertools import combinations

In [2]:
N = int(input())

 3


In [3]:
XnYn = []
for i in range(N):
    A = int(input())
    for _ in range(A):
        X, Y = map(int, input().split())
        XnYn.append((i, X-1, Y))

 2
 2 1
 3 0
 2
 1 1
 3 0
 2
 1 1
 2 1


In [4]:
A = np.array(list(product((0, 1), repeat=N)), np.bool)

In [5]:
A

array([[False, False, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True,  True],
       [ True, False, False],
       [ True, False,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [31]:
A = np.array(list(product((0, 1), repeat=N)), np.bool)
for i, x, y in XnYn:
#     bl = (A[:, i]) | (A[:, x] == bool(y))
    bl = (~A[:, i]) | (A[:, x] == bool(y))
    print(A[:, i], ~A[:, i])
    print(A[:, x])
    print(bl)
    A = A[bl]
    print(A)

[False False False False  True  True  True  True] [ True  True  True  True False False False False]
[False False  True  True False False  True  True]
[ True  True  True  True False False  True  True]
[[False False False]
 [False False  True]
 [False  True False]
 [False  True  True]
 [ True  True False]
 [ True  True  True]]
[False False False False  True  True] [ True  True  True  True False False]
[False  True False  True False  True]
[ True  True  True  True  True False]
[[False False False]
 [False False  True]
 [False  True False]
 [False  True  True]
 [ True  True False]]
[False False  True  True  True] [ True  True False False False]
[False False False False  True]
[ True  True False False  True]
[[False False False]
 [False False  True]
 [ True  True False]]
[False False  True] [ True  True False]
[False  True False]
[ True  True  True]
[[False False False]
 [False False  True]
 [ True  True False]]
[False  True False] [ True False  True]
[False False  True]
[ True False  True]

In [32]:
print(A.sum(axis=1).max())

2


In [6]:
A[:, 0]

array([False, False, False, False,  True,  True,  True,  True])

In [7]:
~A[:, 0]

array([ True,  True,  True,  True, False, False, False, False])

In [8]:
A[:, 1] == bool(1)

array([False, False,  True,  True, False, False,  True,  True])

In [11]:
~A[:, 0] | A[:, 1] == bool(1)

array([ True,  True,  True,  True, False, False,  True,  True])

In [12]:
A[~A[:, 0] | A[:, 1] == bool(1)]

array([[False, False, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [10]:
A[:, 2] == bool(0)

array([ True, False,  True, False,  True, False,  True, False])